### PR TITLE
scala-maven-plugin migration

### PR DESCRIPTION
**Pull request by slandelle**

### CODE REVIEW

**Comment by slandelle** [comment]
@davidB I ping you as I'm not sure you're notified on sonatype repo.
I'd like to migrate from maven-scala-plugin to scala-maven-plugin but I'm stalled as long as m2e-scala doesn't support it.
This patch was tested on eclipse 3.7.2, scala IDE 2.0.0 and scala 2.9.1-1 and everything runs fine.

WDYT?

**Comment by davidB** [comment]
Thanks,

I would like to support both maven-scala-plugin and scala-maven-plugin (to be backward compatible). I'll start from your patch (can't be merge automatically), to at least having a version for user of scala-maven-plugin.

I hope to change and publish a new version next week-end.

**Comment by slandelle** [comment]
Cool!
And thanks a lot for this good work with maven for scala!

**Comment by davidB** [comment]
Hi,

I deployed a version 0.4.0, but I'm not sur it works as expected (I had some issue with my eclipse's setup)
Can you give a try. (update-site: http://alchim31.free.fr/m2e-scala/update-site )

**Comment by slandelle** [comment]
OK, I'm going to try it today and give you some feedback.
Just to let you know, my fix wouldn't work with Scala IDE 2.9.2-RCX, no idea why.

Thanks,

Steph

**Comment by slandelle** [comment]
Done. I had a strange issue: one of the module of my project lost its scala library and I had to add it manually. All the other projects were fine.

If you don't mind, I'll do some more tests tomorrow on a fresh workspace and freshly checked out projects.

**Comment by davidB** [comment]
I had to call "update Configuration" on a existing project.
I tried the version 0.4.0 with the last RC of scala-IDE => scala-ibrary 2.9.2-20120326 with success (but I only have small projects).

"Merci pour ce rapide retour" ;-)

**Comment by slandelle** [comment]
Me too but that failed for one of the modules and eclipse told me to add the library manually.
I'll try again tomorrow with Scala IDE 2.0.0. and 2.0.1-RC2 and let you know the result.

"Y a pas de quoi et merci à toi!"

**Comment by slandelle** [comment]
I've checked m2e-scala 0.4.0 with a fresh workspace and a fresh Scala IDE.
Everything runs fine with Scala IDE 2.0.0 but I can manage to have my projects compile with Scala 2.0.1-RC2.
My scala files are simply not recognized as scala classes...

**Comment by slandelle** [comment]
Just tried with Scala IDE 2.1.0-M1 w/ Scala 2.9.2 and everything runs fine.
Thanks!

**Pull request closed without merging**
